version: "3"

services:
  postgres:
    image: "postgres:latest"
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: "always"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
