// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: languages.sql

package db

import (
	"context"
)

const getLanguageIdByCode = `-- name: GetLanguageIdByCode :one
SELECT
    pk
FROM
    languages
WHERE
    code = $1
`

func (q *Queries) GetLanguageIdByCode(ctx context.Context, code LanguageCode) (int64, error) {
	row := q.db.QueryRow(ctx, getLanguageIdByCode, code)
	var pk int64
	err := row.Scan(&pk)
	return pk, err
}
