// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type LanguageCode string

const (
	LanguageCodeChn LanguageCode = "chn"
	LanguageCodeJp  LanguageCode = "jp"
)

func (e *LanguageCode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LanguageCode(s)
	case string:
		*e = LanguageCode(s)
	default:
		return fmt.Errorf("unsupported scan type for LanguageCode: %T", src)
	}
	return nil
}

type NullLanguageCode struct {
	LanguageCode LanguageCode
	Valid        bool // Valid is true if LanguageCode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLanguageCode) Scan(value interface{}) error {
	if value == nil {
		ns.LanguageCode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LanguageCode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLanguageCode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LanguageCode), nil
}

type OrderStatus string

const (
	OrderStatusPending    OrderStatus = "pending"
	OrderStatusProcessing OrderStatus = "processing"
	OrderStatusShipped    OrderStatus = "shipped"
	OrderStatusDelivered  OrderStatus = "delivered"
	OrderStatusCancelled  OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type ProductStatus string

const (
	ProductStatusInStock      ProductStatus = "in-stock"
	ProductStatusOutOfStock   ProductStatus = "out-of-stock"
	ProductStatusDiscontinued ProductStatus = "discontinued"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus
	Valid         bool // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type Order struct {
	Pk              int64
	ID              pgtype.UUID
	UserPk          int64
	Status          OrderStatus
	IsPaid          bool
	TotalPrice      int32
	ShippingAddress string
	ShippingDate    pgtype.Timestamptz
	DeliveredDate   pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type OrderDetail struct {
	Pk        int64
	OrderPk   int64
	ProductPk int64
	Quantity  int32
	Price     int32
	Discount  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Product struct {
	Pk        int64
	ID        pgtype.UUID
	Price     int32
	Discount  int32
	ImageURLs []string
	Status    ProductStatus
	Quantity  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ProductTranslation struct {
	Pk          int64
	ProductPk   int64
	Language    LanguageCode
	Name        string
	Description string
	Category    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	Pk        int64
	ID        pgtype.UUID
	Email     string
	Phone     string
	Password  string
	FirstName string
	LastName  string
	Language  LanguageCode
	Address   string
	LastLogin pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
