// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: products.sql

package db

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (price, image, status, quantity)
    VALUES ($1, $2, $3, $4)
RETURNING
    pk, id, price, discount, image, status, quantity, created_at, updated_at
`

type CreateProductParams struct {
	Price    int32
	Image    string
	Status   ProductStatus
	Quantity int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Price,
		arg.Image,
		arg.Status,
		arg.Quantity,
	)
	var i Product
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.Price,
		&i.Discount,
		&i.Image,
		&i.Status,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE pk = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, pk int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, pk)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT
    pk, id, price, discount, image, status, quantity, created_at, updated_at
FROM
    products
WHERE
    pk = $1
`

func (q *Queries) GetProduct(ctx context.Context, pk int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, pk)
	var i Product
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.Price,
		&i.Discount,
		&i.Image,
		&i.Status,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
    pk, id, price, discount, image, status, quantity, created_at, updated_at
FROM
    products
LIMIT $1 offset $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.Price,
			&i.Discount,
			&i.Image,
			&i.Status,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE
    products
SET
    price = $2,
    image = $3,
    status = $4,
    quantity = $5
WHERE
    pk = $1
RETURNING
    pk, id, price, discount, image, status, quantity, created_at, updated_at
`

type UpdateProductParams struct {
	Pk       int64
	Price    int32
	Image    string
	Status   ProductStatus
	Quantity int32
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Pk,
		arg.Price,
		arg.Image,
		arg.Status,
		arg.Quantity,
	)
	var i Product
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.Price,
		&i.Discount,
		&i.Image,
		&i.Status,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
